#!/usr/bin/env python3
"""
Life Optimiser — Dashboard Update (runs at 11:20PM Copenhagen time)
Pulls all data, generates AI content via Claude, rebuilds dashboard DATA block,
and pushes to GitHub Pages.
"""

import os
import json
import re
import subprocess
import datetime
from helpers import (
    copenhagen_now, today_str, get_garmin_client, get_garmin_stats,
    get_garmin_activities, get_garmin_training_status, get_garmin_week_data,
    get_gcal_events, get_weather,
    notion_read_page, ask_claude
)

REPO_DIR = "/tmp/life-optimiser-dashboard"
DATA_START_MARKER = "// ===== DATA BLOCK — Regenerated by 11PM scheduled task ====="
DATA_END_MARKER = "// ===== END DATA BLOCK ====="


def clone_repo():
    """Clone the dashboard repo."""
    token = os.environ["GITHUB_TOKEN"]
    repo_url = f"https://x-access-token:{token}@github.com/mwebster0111/life-optimiser-dashboard.git"

    if os.path.exists(REPO_DIR):
        subprocess.run(["rm", "-rf", REPO_DIR])

    subprocess.run(
        ["git", "clone", repo_url, REPO_DIR],
        check=True, capture_output=True
    )
    # Set git identity
    subprocess.run(["git", "config", "user.email", "actions@github.com"], cwd=REPO_DIR)
    subprocess.run(["git", "config", "user.name", "Life Optimiser Bot"], cwd=REPO_DIR)


def push_changes(message):
    """Commit and push changes to the repo."""
    subprocess.run(["git", "add", "-A"], cwd=REPO_DIR, check=True)
    result = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=REPO_DIR, capture_output=True
    )
    if result.returncode == 0:
        print("No changes to commit.")
        return
    subprocess.run(["git", "commit", "-m", message], cwd=REPO_DIR, check=True)
    subprocess.run(["git", "push"], cwd=REPO_DIR, check=True)
    print(f"Pushed: {message}")


def build_activities_data(activities):
    """Convert Garmin activities to dashboard format."""
    result = []
    for a in activities[:10]:
        name = a.get("activityName", "Activity")
        dist = round(a.get("distance", 0) / 1000, 2)
        dur_secs = a.get("duration", 0)
        if dur_secs > 3600:
            dur = f"{int(dur_secs // 3600)}h {int((dur_secs % 3600) // 60)}m"
        else:
            dur = f"{int(dur_secs // 60)}m {int(dur_secs % 60)}s"

        avg_hr = a.get("averageHR", 0) or 0
        max_hr = a.get("maxHR", 0) or 0
        cals = a.get("calories", 0) or 0

        # Pace for running activities
        pace = ""
        if dist > 0 and "run" in name.lower():
            pace_secs = dur_secs / dist
            pace = f"{int(pace_secs // 60)}:{int(pace_secs % 60):02d}/km"

        result.append({
            "date": a.get("startTimeLocal", "")[:10],
            "name": name,
            "dist": dist,
            "duration": dur,
            "avgHR": avg_hr,
            "maxHR": max_hr,
            "pace": pace,
            "calories": cals,
        })
    return result


def build_running_data(training, activities):
    """Build running stats for dashboard."""
    ts = training.get("training_status") or {}
    rp = training.get("race_predictions")

    # Parse race predictions
    predictions = {"fiveK": "--:--", "tenK": "--:--", "half": "--:--:--", "marathon": "--:--:--"}
    if rp:
        pred_list = rp if isinstance(rp, list) else [rp]
        for pred in pred_list:
            if isinstance(pred, dict):
                for key in pred:
                    val = pred[key]
                    if isinstance(val, dict):
                        secs = val.get("predictedTimeSeconds") or val.get("time")
                        if secs:
                            h = int(secs // 3600)
                            m = int((secs % 3600) // 60)
                            s = int(secs % 60)
                            formatted = f"{h}:{m:02d}:{s:02d}" if h > 0 else f"{m}:{s:02d}"
                            dist = val.get("distance") or val.get("raceDistance", {}).get("distance", 0)
                            if dist:
                                dist_km = dist / 1000 if dist > 100 else dist
                                if abs(dist_km - 5) < 1:
                                    predictions["fiveK"] = formatted
                                elif abs(dist_km - 10) < 1:
                                    predictions["tenK"] = formatted
                                elif abs(dist_km - 21.1) < 1:
                                    predictions["half"] = formatted
                                elif abs(dist_km - 42.2) < 1:
                                    predictions["marathon"] = formatted

    # Weekly running stats
    week_km = 0
    week_runs = 0
    today = datetime.date.fromisoformat(today_str())
    week_start = today - datetime.timedelta(days=today.weekday())
    for a in activities:
        act_date = a.get("startTimeLocal", "")[:10]
        if act_date >= week_start.isoformat() and "run" in (a.get("activityName", "") or "").lower():
            week_km += (a.get("distance", 0) or 0) / 1000
            week_runs += 1

    acute = ts.get("acuteTrainingLoad", 0) or 0
    chronic = ts.get("chronicTrainingLoad", 0) or 0
    ratio = round(acute / chronic, 2) if chronic > 0 else 0

    load_status = "Optimal"
    if ratio > 1.5:
        load_status = "High Risk"
    elif ratio > 1.3:
        load_status = "Caution"
    elif ratio < 0.8:
        load_status = "Detraining"

    return {
        "prs": {"fiveK": "--:--", "tenK": "--:--"},
        "predictions": predictions,
        "vo2max": ts.get("vo2MaxValue", 0) or 0,
        "weeklyKm": round(week_km, 1),
        "weekRuns": week_runs,
        "trainingStatus": ts.get("trainingStatusPhrase", "Unknown"),
        "acuteLoad": round(acute),
        "chronicLoad": round(chronic),
        "loadRatio": ratio,
        "loadStatus": load_status,
        "balance": ts.get("trainingLoadBalancePhrase", "N/A") or "N/A",
    }


def build_schedule_data(events, date_info):
    """Convert calendar events to dashboard schedule format."""
    today = today_str()
    tomorrow = (datetime.date.fromisoformat(today) + datetime.timedelta(days=1)).isoformat()
    day_after = (datetime.date.fromisoformat(today) + datetime.timedelta(days=2)).isoformat()

    days = {}
    for event in events:
        start = event["start"]
        event_date = start[:10] if len(start) >= 10 else ""

        if event_date == today:
            label = "Today"
        elif event_date == tomorrow:
            dt = datetime.date.fromisoformat(tomorrow)
            label = dt.strftime("%A")
        elif event_date == day_after:
            dt = datetime.date.fromisoformat(day_after)
            label = dt.strftime("%A")
        else:
            continue

        if label not in days:
            days[label] = []

        time_str = ""
        if not event["all_day"]:
            time_str = start[11:16] if len(start) > 11 else ""

        # Color dot based on event type
        summary = event["summary"].lower()
        if any(w in summary for w in ["thesis", "study", "work", "everllence"]):
            dot = "var(--purple)"
        elif any(w in summary for w in ["run", "train", "gym", "exercise"]):
            dot = "var(--green)"
        elif any(w in summary for w in ["meet", "call", "sync"]):
            dot = "var(--blue)"
        else:
            dot = "var(--orange)"

        days[label].append({
            "time": time_str,
            "name": event["summary"],
            "dot": dot,
        })

    # Sort and format
    order = ["Today"]
    if tomorrow:
        dt = datetime.date.fromisoformat(tomorrow)
        order.append(dt.strftime("%A"))
    if day_after:
        dt = datetime.date.fromisoformat(day_after)
        order.append(dt.strftime("%A"))

    result = []
    for label in order:
        if label in days:
            result.append({"label": label, "events": days[label]})

    return result


def generate_ai_content(garmin_summary, trends, activities, events, weather, running_data):
    """Use Claude to generate suggestions, training plan, food, patterns, habits."""
    today = today_str()
    date_info = copenhagen_now()
    day_name = date_info["day_of_week"]

    # Read Notion context
    goals = notion_read_page("goals")
    constraints = notion_read_page("constraints")
    weekly_plan = notion_read_page("weekly_plan")
    preferences = notion_read_page("preferences")
    personality = notion_read_page("personality")

    trends_str = json.dumps(trends, indent=2)
    activities_str = json.dumps([{
        "name": a.get("activityName", ""),
        "date": a.get("startTimeLocal", "")[:10],
        "distance": round(a.get("distance", 0) / 1000, 2),
        "duration": a.get("duration", 0),
    } for a in activities[:7]], indent=2)

    prompt = f"""You are the Life Optimiser AI for Michael Webster, a student athlete in Copenhagen.

Today is {day_name}, {today}.

HEALTH DATA (7-day trends):
{trends_str}

RECENT ACTIVITIES:
{activities_str}

RUNNING STATS:
VO2max: {running_data['vo2max']}, Training status: {running_data['trainingStatus']}
Weekly: {running_data['weeklyKm']}km across {running_data['weekRuns']} runs
Acute load: {running_data['acuteLoad']}, Chronic: {running_data['chronicLoad']}, Ratio: {running_data['loadRatio']}

WEATHER:
{json.dumps(weather, indent=2)}

GOALS & PRIORITIES:
{goals}

CONSTRAINTS:
{constraints}

WEEKLY PLAN:
{weekly_plan}

PREFERENCES:
{preferences}

PERSONALITY:
{personality}

Generate the following JSON sections for Michael's Life Optimiser dashboard. Return ONLY valid JSON with these exact keys:

{{
  "suggestions": [
    {{"cat": "category_name", "color": "css_color_var", "bg": "css_bg_var", "text": "suggestion text"}}
  ],
  "patterns": [
    {{"text": "pattern observation"}}
  ],
  "trainingPlan": [
    {{
      "day": "Day Name",
      "type": "Easy Run|Intervals|Long Run|Rest|Strength|Cross-Train",
      "typeColor": "css_color_var",
      "typeBg": "css_bg_var",
      "session": "session title",
      "details": "session details",
      "rationale": "why this session",
      "stats": ["stat1", "stat2"]
    }}
  ],
  "food": {{
    "mealSuggestions": [
      {{
        "name": "Meal Name",
        "time": "Breakfast|Lunch|Dinner|Snack",
        "reason": "why this meal",
        "tags": [{{"label": "tag", "color": "css_color_var", "bg": "css_bg_var"}}]
      }}
    ],
    "pantryHighlights": ["ingredient1", "ingredient2"],
    "nutritionContext": "brief nutrition context based on training",
    "targets": {{"calories": "target", "protein": "target", "focus": "focus area"}}
  }},
  "habitStreaks": [
    {{
      "name": "habit name",
      "days": [0, 1, 1, 1, 0, 1, 1],
      "labels": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      "streak": "N days",
      "target": 7
    }}
  ],
  "thesis": {{
    "dueDate": "YYYY-MM-DD",
    "daysRemaining": N,
    "topic": "thesis topic from context",
    "chapters": [
      {{"num": 1, "name": "Chapter Name", "status": "status", "pct": 0-100, "color": "css_color_var"}}
    ],
    "keyTasks": [
      {{"text": "task", "done": true/false}}
    ]
  }},
  "everllence": {{
    "hoursThisWeek": N,
    "weekTarget": N,
    "hoursThisMonth": N,
    "monthTarget": N,
    "note": "context note"
  }}
}}

CRITICAL RULES:
- Training plan should cover 3 days starting from tomorrow
- NEVER schedule Everllence on Saturday or Sunday — it is Monday-Friday only
- Use these CSS color vars: var(--purple), var(--red), var(--blue), var(--orange), var(--green), var(--teal), var(--pink), var(--yellow)
- And bg vars: var(--purple-bg), var(--red-bg), var(--blue-bg), var(--orange-bg), var(--green-bg), var(--teal-bg), var(--pink-bg), var(--yellow-bg)
- Base suggestions, patterns, food on REAL data — not fabricated numbers
- Include 3-5 suggestions covering health, training, productivity
- Include 3-4 pattern observations from the 7-day data
- Include 3-4 meal suggestions based on training load and recovery needs
- Include 3-5 habit streaks (sleep 7h+, 8000+ steps, training, hydration, etc.)
- Thesis/Everllence data should match what's in the Notion context
- Return ONLY the JSON, no explanation"""

    response = ask_claude(prompt, max_tokens=4000)

    # Parse JSON from response
    try:
        # Try direct parse first
        data = json.loads(response)
    except json.JSONDecodeError:
        # Try to extract JSON from markdown code block
        match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', response, re.DOTALL)
        if match:
            data = json.loads(match.group(1))
        else:
            # Try to find JSON object
            start = response.find('{')
            end = response.rfind('}') + 1
            if start >= 0 and end > start:
                data = json.loads(response[start:end])
            else:
                raise ValueError(f"Could not parse JSON from Claude response: {response[:200]}")

    return data


def build_full_data(trends, activities_data, running_data, schedule, weather, ai_content, date_info):
    """Assemble the complete DATA object for the dashboard."""
    today = today_str()

    data = {
        "meta": {
            "lastRefresh": f"{date_info['day_of_week']}, {today} at 23:20",
            "today": today,
            "dayLabel": date_info["day_of_week"],
            "location": "Copenhagen, Denmark",
            "locationNote": "55.68°N, 12.57°E",
        },
        "healthTrends": trends,
        "activities": activities_data,
        "running": running_data,
        "schedule": schedule,
        "weather": weather,
        "suggestions": ai_content.get("suggestions", []),
        "patterns": ai_content.get("patterns", []),
        "trainingPlan": ai_content.get("trainingPlan", []),
        "food": ai_content.get("food", {}),
        "habitStreaks": ai_content.get("habitStreaks", []),
        "thesis": ai_content.get("thesis", {}),
        "everllence": ai_content.get("everllence", {}),
    }
    return data


def inject_data_into_html(html, data):
    """Replace the DATA block in the dashboard HTML."""
    data_json = json.dumps(data, indent=2, ensure_ascii=False)
    new_block = f"{DATA_START_MARKER}\nconst DATA = {data_json};\n{DATA_END_MARKER}"

    # Find and replace the data block
    pattern = re.escape(DATA_START_MARKER) + r'.*?' + re.escape(DATA_END_MARKER)
    new_html = re.sub(pattern, new_block, html, flags=re.DOTALL)

    if new_html == html and DATA_START_MARKER not in html:
        raise ValueError("Could not find DATA block markers in HTML!")

    return new_html


def main():
    date_info = copenhagen_now()
    print(f"Dashboard Update starting — {date_info['full_output']}")

    # Clone repo
    print("Cloning dashboard repo...")
    clone_repo()

    # Read current HTML
    html_path = os.path.join(REPO_DIR, "index.html")
    with open(html_path, "r") as f:
        html = f.read()

    # Pull all data
    print("Connecting to Garmin...")
    garmin = get_garmin_client()
    today = today_str()
    fourteen_days_ago = (datetime.date.fromisoformat(today) - datetime.timedelta(days=14)).isoformat()

    print("Pulling Garmin data...")
    stats = get_garmin_stats(garmin, today)
    training = get_garmin_training_status(garmin)
    activities = get_garmin_activities(garmin, fourteen_days_ago, today)
    trends = get_garmin_week_data(garmin, 7)

    print("Pulling calendar...")
    try:
        events = get_gcal_events(days_ahead=3)
    except Exception as e:
        print(f"Warning: Calendar failed: {e}")
        events = []

    print("Pulling weather...")
    weather = get_weather(7)

    # Build structured data
    activities_data = build_activities_data(activities)
    running_data = build_running_data(training, activities)
    schedule = build_schedule_data(events, date_info)

    # Generate AI content
    print("Generating AI content via Claude...")
    garmin_summary = json.dumps({
        "stats": stats.get("stats", {}),
        "sleep": stats.get("sleep", {}).get("dailySleepDTO", {}),
    }, default=str)
    ai_content = generate_ai_content(garmin_summary, trends, activities, events, weather, running_data)

    # Build full DATA object
    data = build_full_data(trends, activities_data, running_data, schedule, weather, ai_content, date_info)

    # Inject into HTML
    print("Injecting data into dashboard...")
    new_html = inject_data_into_html(html, data)

    # Write and push
    with open(html_path, "w") as f:
        f.write(new_html)

    print("Pushing to GitHub Pages...")
    push_changes(f"Dashboard update — {date_info['day_of_week']} {today}")

    print("Dashboard update complete!")
    print(f"View at: https://mwebster0111.github.io/life-optimiser-dashboard/")


if __name__ == "__main__":
    main()
